---

name: telegram jobs report
on: [push]

jobs:
  build:
    defaults:
      run:
        working-directory: ./.github/workflows/report_jobs

    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: get available jobs
        shell: bash
        run: |
          ./report_jobs.sh > raw
          cat ./raw

      - name: send jobs report to osscameroon group
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_OSSCAMEROON_GROUP_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: MarkdownV2
          message_file: ./.github/workflows/report_jobs/raw
