---

name: telegram github opencollective report
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 13 26 * *"

jobs:
  build:
    defaults:
      run:
        working-directory: ./.github/workflows/opencollective_contributions

    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: get contribution report
        shell: bash
        run: |
          ./get_opencollective_info.sh > contributions_report_message

      - name: send opencollective contribution report to osscameroon channel
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_OSSCAMEROON_CHANNEL_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: MarkdownV2
          message_file: |
            ./.github/workflows/opencollective_contributions/contributions_report_message

      - name: send opencollective contribution report to osscameroon group
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_OSSCAMEROON_GROUP_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: MarkdownV2
          message_file: |
            ./.github/workflows/opencollective_contributions/contributions_report_message
