---

name: validate message scheduler messages
on:  # yamllint disable-line rule:truthy
  - pull_request:
    branches:
      - main
    paths:
      - .github/workflows/social_media_message_scheduler/**
      - .github/workflows/validate_message_scheduler_messages.yaml

jobs:
  send-message:
    defaults:
      run:
        working-directory: ./.github/workflows/social_media_message_scheduler

    name: Validate messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          make install-deps

      - name: Validate
        run: |
          make validate
